### ISSUE TITLE
Getting locked out of project when upgrading to OpenRefine 2.6

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#141]
I upgraded from Google Refine 2.5 to OpenRefine 2.6. Before upgrading I left a project checked out to myself. When I opened 2.6, I found that the project appeared as if it was checked out to another user, even though it said it was checked out to me. I went back into 2.5 and found that I could still access the project there. I checked it back in, and then found I was able to check it out it in 2.6. 

This bug will probably not affect many users, but it would be nice to get it sorted out.

**Comment by sosguthorpe** [comment]
This isn't actually a bug with the module we have. This is just a by-product of upgrading from Google Refine to OpenRefine. The developers of refine changed the data directory where refine keeps everything and it's something that is out of my hands. I will have a think about what I might be able to do to help with this, but it is low priority for now.

As soon as I replied to this it occurred to me that the real issue here is that a project being checked out somewhere should still allow the same user to check that out again in a different version of refine or on another machine. This could open a whole new can of worms with integrity of data. Still making this low priority for now but certainly needs thinking about and addressing.
