### ISSUE TITLE
Ref Data Category Labels

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#193]
Include the label / description used in web forms in the definition form. Add a note about the label in Admin form and / or link from label back from the Admin form

**Comment by ianibo** [comment]
because refdata categories can have different labels depending upon where they are used [For example, we have a refdata category YNO for yes, no, other which could be used in fields called ILLAllowed, FairUse, etc, etc there is not 1 label for a category. This means that allowing an admin to edit a label might lead to unexpected side effects. Therefore, labels are best left in their current form. However, commit https://github.com/k-int/gokb-phase1/commit/031e1c2199295ef0ece3d2e0b662d784f4c00edc adds a "Refdata Values" link which only admins see. This adds a link to the refdata category by the side of any refdata field, making it easy for the admin to edit the refdata set for a given field.

**Comment by kristenwilson** [comment]
Confirmed that this is working.
