### ISSUE TITLE
Fix user profile permissions

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#228]
Currently, the user profile permissions are the same as the permission to view/create/edit/delete users. We need a separate permission so that people can modify their own profiles, even if they don't have permission to see/edit the list of users.

**Comment by sosguthorpe** [comment]
I think that globally users are allowed to edit themselves. They can't however change their own permissions. I think the issue here is that some users have no way to get to the edit users screen to change their own data.

I think we should change the current "My profile" screen to include the user details view for the current user as well as the "change password" function. The preferences should probably be moved to a different screen as they are not really about "me" but more about customizing my GOKb experience. Both these screens should be accesed by clicking on the User icon top-right.

**Comment by kristenwilson** [comment]
I'm fine with the changes you've proposed, Steve. I just want to clarify that, currently, users cannot edit the "my profile" preferences unless they also have edit rights for the Users domain. These need to be separated, because I don't plan to grant most users rights to edit this domain.

**Comment by sosguthorpe** [comment]
Fixed in 4.x
