### ISSUE TITLE
Fix ISSN matching and create Refine warning message for ISSN conflicts

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#243]
Per today's call, we need two fixes related to ISSN data quality.
1. In Refine, query GOKb to determine if there is a conflict between the ISSN type in a project and the ISSN type already in the CRED. (I.e., in a project, 1234-5678 is listed as an ISSN, but in the CRED it is listed as an e-ISSN). Create a Refine warning message that says something like "One or more ISSNs conflicts with the ISSN type already found in GOKb." We will need an identical warning message for e-ISSNs.
2. When ingesting titles, ISSN matches should be made against both the ISSN and e-ISSN namespaces and merged accordingly. So if 1234-5678 is listed as an e-ISSN in a project, but matches a p-ISSN already in GOKb, a match should be made and the titles merged. If this creates a TI that has the same value for e-ISSN and p-ISSN, a review task should be created.

Note: I think this needs to be a warning in Refine, b/c it's possible that the error could be with the title already in GOKb, and cannot be fixed with the import. That is why it is important to have both the Refine warning and the review task.

**Comment by ianibo** [comment]
Ian and steve to review --

**Comment by sosguthorpe** [comment]
@kristenwilson I have been thinking about this and surely a better approach would be to make this an error instead of a warning and ensure the data is correct before ingesting?. This would mean either modifying the title in CRED so that the correct ISSN type is set in there or rectifying the refine row depending on which is correct.

I see this as a better solution than allowing an ingest, when we know 100% that one of the views of data is wrong, and then raising a review request. What do you think?

I'd be interested to hear from @ostephens too!

**Comment by ostephens** [comment]
My view would be part (2) of this is higher priority because resolving (2) stops us duplicating TIs in the data. I'd suggest as part of this work we should consider incorporating the ISSN-L table which maps both pISSN and eISSN to a common 'ISSN-L'

On (1) I'm with @kristenwilson that this has to be a warning in Refine - I don't think the person doing the import will always want to resolve this at point of import.

The other comment/question I have is whether we want to record erroneous assertions about ISSNs or not - so if a publisher states 1234-5678 is the pISSN when it is really the eISSN do we want to record they do this, or do we not care as long as we match to the correct TI on import?

**Comment by kristenwilson** [comment]
I agree that (2) is the higher priority. Essentially, it means that we are treating all ISSNs as a single namespace when it comes to merging. And that will eliminate the largest problem we're having right now, which is duplication of TIs when importing titles with incorrectly labeled ISSNs. If we implement (2), then we solve the problem of duplication, and (1) gives users the option to fix the mislabeling issue in Refine, but allows them to defer to the CRED if they want to.

I'd also like to see the ISSN-L table implemented, but I'm OK with doing that in a later release if it's too far beyond the scope of this issue.

We have another issue #233 that is an umbrella for dealing with repeated errors. The question how how to handle repeat mislabeled ISSNs might be part of that.

**Comment by sosguthorpe** [comment]
I have I have addressed the ingest part of this (part 2).

A review request is raised when a title is matched using an identifier value that has a different declared type in CRED and the Refine data. The review request details the type declared in the project vs. the type found in CRED.

**Comment by kristenwilson** [comment]
I have confirmed that the functionality described in part 2 is now working as expected.

Are you intending to code part 1 as well or should I close this and open part 1 as a separate issue for later on?

**Comment by sosguthorpe** [comment]
I think we should create a new issue for the next release.

**Comment by kristenwilson** [comment]
Opened #395 to cover part 1 of this.
