### ISSUE TITLE
No projects available for check-out in Refine

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#25]
Since update of data this morning now not seeing projects to check-out. Error message "There are currently no GOKb projects available for checkout.":
![screen shot 2013-08-19 at 11 33 46](https://f.cloud.github.com/assets/576174/985372/f3709270-08ba-11e3-87cf-d5ab27d0124b.png)

**Comment by sosguthorpe** [comment]
New data model for project has an "rp_project_status" field that now contains a status rather than just a "checked_in" flag. Propose we set all projects to "CHECKED_IN" where we don't have a status.

For a push to Kuali we'll need to be a little more clever. As we'll need to persist checkout information after the update.

**Comment by sosguthorpe** [comment]
Leaving open as a reminder for Kuali transfer.

**Comment by ianibo** [comment]
Updated -live- with SQL from @sosguthorpe : 

UPDATE kbcomponent SET rp_created_by=1, rp_last_checked_out_by=1, rp_modified_by=1, rp_project_status='CHECKED_IN' WHERE class='org.gokb.refine.RefineProject';

**Comment by ostephens** [comment]
Confirmed projects now visible thanks
