### ISSUE TITLE
Unnecessary system message generated when renaming columns in Refine

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#260]
When you use the quick resolution feature in Refine to rename a column, you will get a confirmation that the column have been renamed, but also a system message stating that the original column does not exist. This second message does not need to be generated -- since you are renaming the column, it makes sense that the original column name would not be present.

Example:
![rename-error](https://cloud.githubusercontent.com/assets/7397776/4847898/2653c894-6056-11e4-8e54-82c27c1d658d.png)

**Comment by sosguthorpe** [comment]
I'm having trouble replicating this one....
Did you clear your caches after installing the new client again? Browsers have a tendency to cache everything.

**Comment by kristenwilson** [comment]
Yes, I cleared the cache first and did a shift+refresh when I opened the new client.

**Comment by kristenwilson** [comment]
I'm still getting this error when I work in Refine, and I noticed it in the screencast that Owen recorded as well. It's behaving exactly the same way as originally described.

**Comment by sosguthorpe** [comment]
This is coming from refine core. Not our module and I'm thinkning that this is to do with the problems refine has with larger amounts of metadata.

**Comment by kristenwilson** [comment]
So it sounds like we are in a bind here whether either:
- We include extra metadata which makes the files too big for Refine to handle well; OR
- We ditch the extra metadata, but then we lose functionality.

Do you two favor one option over the other? Do you think creating this larger files is going to lead to additional trouble in the future or will it be confined to this one issue? This may need some discussion.

**Comment by ostephens** [comment]
I'd be really surprised if the issue is with the amount of metadata - Steve can you explain why this might cause the issue?

I can't recreate the issue reliably - it doesn't always happen using the 'quick resolution' rename

**Comment by sosguthorpe** [comment]
I'd be happy to explain the problems. But, for the sake of clarity, I'm not saying it is definitely the problems refine is showing with the metadata causing this issue but "could" be, and is the path I'm investigating first.

So now we have more metadata (the source file is embedded in there) refine is exhibiting some strange behaviours in some cases.

I managed to track an error with the project check-in process to a problem caused by the amount of data. When checking in a project the module uses refine core functionality to export the project and the flow looks like this:
- Save the project (refine core)
- Export the project (refine core)
- Upload to server
- Act on server response.

Now, when refine is saving the project it save the metadata to a temporary file then overwrites the old metadata file once it has succeeded (to try and make sure it doesn't overwrite the old metadata unless save was successful). However, the temporary file is stored in the project folder (really it should be in a temp folder). So the next call to export the project if finding that temporary file (as the large amount of data means refine is still writing to disk) and adds it to a list of files to export. However, by the time it comes to actually add the temporary file to the zip export that file has been removed (as the write had finished) and an error is thrown.

As this error is coming from the project model returning null for a column value I thought it could be due to an ongoing update/refresh to the model caused by the increase in latency of metadata writing.

I haven't fully investigated, but it is definitely something that could cause issues.

**Comment by sosguthorpe** [comment]
@kristenwilson I'm investigating this issue again today and hopefully will be able to track down why this is happening today. There should be something we can do, even if it's only temporarily suppressing the error while a more permanent fix is implemented. So I don't think there is any need for discussion at the moment.

**Comment by ostephens** [comment]
Thanks Steve - that explanation definitely makes sense to me now

**Comment by sosguthorpe** [comment]
Managed to track this down, and it isn't related to the saving of the metadata which is good news. Instead this is to do with the library that makes the buttons look uniform within the html forms. It's wrapping buttons in another element and adding the "click" functionality to that element. If you click on the very left hand side of the button both the click event fire on the wrapper and the button itself causing the rename function to fire twice in quick succession, whhich causes the second execution to fail as the column has already been renamed. Looking into a fix now.

pixelmatrix/uniform/issues/328
