### ISSUE TITLE
Org not showing anything on Published Titles tab

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#272]
See #148 

The Published Titles tab on the Org record is not showing anything on the Published Titles tab, even when related published titles exist. 

Example:
Taylor and Francis org record: https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.Org%3A2095
Taylor and Francis package contains 38 titles that all have T&F listed as a publisher: https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.Package%3A37779

**Comment by ianibo** [comment]
This is because we have changed the way publishers work - they are no longer stored directly against the  title, but a list with dates. We removed "CurrentPublisher" recently. This list of records works off the "currentPublisher" link which is now discontinued. We can write a new query to look at the new structure -but this will take  alittle time..
