### ISSUE TITLE
Reviews tasks created in error when updating a package

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#276]
For testing purposes, I ingested the package Springer: Complete Journals: 20141030 twice. The first time through, behavior was completely normal. The second time through, the system created about 550 review tasks of the type: TIPP Not present when performing package update. This is strange because I ingested the exact same list of TIPPs both times. There were not any TIPPs in the original ingest that would have been left out the second time through. Can we check on why all of these review tasks were created?

**Comment by kristenwilson** [comment]
Just an update that users are seeing this behavior with GOKb 3.0.5 as well, so it may not be a new bug introduced with 4.0, but an existing issue. 

Here are two examples of review tasks that were created in GOKb 3.0.5. These TIPPs were part of the original ingest file from Refine, as well as the updated file ingested a month later.
https://gokb.kuali.org/gokb/resource/show/org.gokb.cred.ReviewRequest%3A274
https://gokb.kuali.org/gokb/resource/show/org.gokb.cred.ReviewRequest%3A311

**Comment by kristenwilson** [comment]
KW -- attach package file here.

**Comment by sosguthorpe** [comment]
OK So after much testing of this issue I have finally got it to behave like you have reported, but the behaviour is totally expected.

I used the "Springer: Complete Journals: 20141030" file that I exported from the K-Int test system to test with on my local copy. I ingested it... Cleared my open reviews and ingested again it raised 4 review tasks. 2 of these are because of duplicate titles with completely different ids (which I put down to before when the title matching on text wasn't quite working), so I disregarded these. Another 2 tipps were legitimate tipps that were created by another project. 2 projects referencing and updating the same package. The second project contained 2 tipps the one I just ingested didn't and hence the 2 review requests.

I would think that this is probably the same reason the review requests were generated on live as you noted above.

2 projects referencing the same package also explains the behaviour you saw on the k-int test system.
I think we can chalk the 550 generations down to the a problem we fixed as this seems to be a freak occurance.

If we look at the package in the test system: https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.Package%3A38095
We can see that there are 2935 titles listed here.
But the project in refine only contains 2934 rows (so I would expect an ingest to generate a single review request) which I can confirm that it did.

My conclusions here is that this functionality appears to be working correctly now. However they're may be a need to discuss what is the expected behaviour when more than 1 project reference the same package.

**Comment by ostephens** [comment]
The behaviour you describe here sounds right to me - so if the original issue (creation of 550 review requests) was fixed, is there anything further to fix here?

**Comment by kristenwilson** [comment]
The individual examples Steve gives all make sense to me as well. This review task serves a legitimate purpose in those types of cases. It's the the creation of large numbers of this review task where no logical explanation is present that is the problem. If you feel confident that that part of the issue is fixed, then I think this can be closed. We will keep an eye out for any recurrences.

**Comment by kristenwilson** [comment]
I believe I saw this happen again in GOKb Live with a project I ingested last week. Since I cannot currently access GOKb Live (and problems there won't be fixed until the next release is pushed out), I propose we table this for now. I will test again once the new release is ready.

**Comment by kristenwilson** [comment]
Bumping this to 4.1 b/c it needs more investigation.

**Comment by kristenwilson** [comment]
I had another report of this issue occurring yesterday. Tessa ingested a project that generate the review tasks found here: https://gokb.kuali.org/gokb/search/index?qbe=g%3AreviewRequests&qp_status=&qp_project=org.gokb.refine.RefineProject%3A152228&qp_raisedby=&qp_allocatedto=&qp_showDeleted=on

All of these review tasks are the "This TIPP was not present..." variety. However, we've done a good bit of spot checking and found that for every one we've looked at the TIPP actually was present in the update being loaded. So these TIPPs are continuing to be generated in error. I'm not seeing any pattern to when this happens, since most ingests aren't producing the issue. Any ideas?

**Comment by sosguthorpe** [comment]
I'm pretty sure this is down to a database read failing and an exception being thrown that we were seeing before the performance improvements that were rolled out just before Christmas. Leaving open, to keep an eye out but I'm fairly confident this should not be raised in error now. Please feel free to correct me if there is evidence to suggest otherwise.

**Comment by kristenwilson** [comment]
Thanks, Steve. I'll continue to keep an eye on it.

Kristen

On Wed, Jan 7, 2015 at 5:59 AM, sosguthorpe notifications@github.com
wrote:

> I'm pretty sure this is down to a database read failing and an exception
> being thrown that we were seeing before the performance improvements that
> were rolled out just before Christmas. Leaving open, to keep an eye out but
> I'm fairly confident this should not be raised in error now. Please feel
> free to correct me if there is evidence to suggest otherwise.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/276#issuecomment-69007052.

## 

Kristen Wilson
Associate Head, Acquisitions and Discovery
GOKb Editor
North Carolina State University Libraries
919-513-3354
kristen_wilson@ncsu.edu

**Comment by kristenwilson** [comment]
We've had more reports of this issue cropping up again. An example from Jan. 29 is Refine project   Elsevier: ScienceDirect Backfile Package - Medicine and Dentistry 1995-2004: 20150129.

When this project was ingested, it produced over 200 "TIPP not present" review tasks. But when the user investigated these titles, she found that all of the titles were present both in the Refine project and the existing package in the CRED.

It's very important that we resolve this issue. People are starting to ignore these review tasks entirely because they are errors about 90% of the time.

**Comment by kristenwilson** [comment]
More reports of this issue today: Elsevier: ScienceDirect Small Multidisciplinary Collection (6 review tasks) and Elsevier: ScienceDirect College Edition Journals Collection - Physical Sciences (354 tasks!!)

**Comment by kristenwilson** [comment]
Another report of this problem from yesterday. I loaded the project Elsevier: ScienceDirect Freedom Collection: 20140205. This generated 315 TIPP not present review tasks out of 2234 titles. I spot-checked 10 of these review tasks and found that in all cases, the TIPP was present in the original project. The other data point I can offer is that when I looked at a handful of review tasks listed consecutively, they corresponded to a sequential group of titles from the refine project. So the first few review tasks listed corresponded to rows 738-786. The last few review tasks corresponded to row numbers 529-532. So it seems as if a consecutive group of titles from the original project was affected.

Strangely, when I look at a TIPP associated with one of the erroneous review tasks, the last updated date does correspond to the ingest that generated the review tasks. So, while GOKb is telling me that the TIPP was not present in the update I just did, the system actually _is_ updating that same TIPP.

Here's an example:
- Review task: https://gokb.kuali.org/gokb/resource/show/org.gokb.cred.ReviewRequest%3A10654
- TIPP: https://gokb.kuali.org/gokb/resource/show/org.gokb.cred.TitleInstancePackagePlatform%3A69682
