### ISSUE TITLE
Add ability to designate primary and secondary values for menus and ref data

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#289]
Per Ian, we should be able to implement the ability to assign a "primary" or "secondary" label to the values for menus and refdata categories. This should bump the primary items to the top of the display, followed by a horizontal rule, then by the secondary items.

**Comment by sosguthorpe** [comment]
I can see the value of this for the menus, but do we really want this for refdata lists too? Where would that be used?

**Comment by ianibbo** [comment]
I think it's because some of the RDVs have quite a lot of options, but
often only 1 or 2 are actually used.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by sosguthorpe** [comment]
See #288

**Comment by kristenwilson** [comment]
I am not sure how to test this, since there doesn't seem to be a field in the system for designating something as primary vs. secondary. I'm also not sure how to edit the order of the menu items at all.

**Comment by sosguthorpe** [comment]
There was always a "type" parameter for domain objects that was used for this. The values weren't "primary" etc though. I have now changed the values using the refdata category edit screen (https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.RefdataCategory%3A44). The sortkey value on this screen controls the order of the menu sections. So now the sections "primary", "secondary", and "tertiary" have been configured to appear in that order. If a menu section doesn't have anything assigned it will not be output to the screen. Everything is defaulted to be in the secondary section. "Secondary" was chosen as the default as this means items can easily be placed in a section above or below the default.

To move an item into a different section we need to select the "Domain" for the menu item. I went to the domain search page and selected the "TitleInstance" element to move the "Title" menu item into a different section (https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.KBDomainInfo%3A21)
From this screen I then simply select "Primary" from the "Type/Category" values and this changes the menu placement. The sort order item also found on this page (defaulted to 0) controlls the order of items within their designated sections.

**Please Note:** The menu items will not move until you sign out and back in. This is because the menus are stored in your user session to minimise the number of DB calls made during a page view.

**Comment by kristenwilson** [comment]
Confirmed fixed
