### ISSUE TITLE
Hide deleted TI-Publisher combos from the Publishers tab of the TI

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#295]
Currently, on the TI record, you can change the status of a publisher-TI combo to deleted. Can we hide the deleted combos by default and add a toggle switch to show deleted (as in search results)?

**Comment by iyawnis** [comment]
Having it hidden by default would require a lot of work, due to the generic nature of the controller. Although changing the Show Deleted option, will automatically refresh the page, and keep you on publisher tab, minimizing interruption.

**Comment by kristenwilson** [comment]
Does this mean we can have the "show deleted" option present for these combos and toggled off by default? I would be fine with that solution.

**Comment by iyawnis** [comment]
By default the deleted combos are visible. This is on dev branch.

![screenshot from 2015-02-17 10 15 46](https://cloud.githubusercontent.com/assets/2336352/6226519/0c85343c-b68e-11e4-9e46-970b18cb46b0.png)

**Comment by kristenwilson** [comment]
Many of the other screens do have this toggle on by default, so it really would be ideal to have this behave the same way. But If it's a lot of extra work, then I agree this is probably not the area we want to spend that effort on.

**Comment by ianibo** [comment]
We may think about backing this out and using http://java.dzone.com/articles/grails-using-hibernate-filters .. investigating

**Comment by ianibo** [comment]
Filter plugin works at the SQL level, not the domain model level, and struggles with filtering through joined associations [status.value != 'deleted']. Sticking with this solution for now. The difference with other screens is that they are search screens rather than record display screens [Usually]. Where display screens allow this kind of filtering [eg titles in a package] it's actually a reuse of the query mechanism. In theory we could allow the search form to be used on this component. Need to discuss this with @sosguthorpe .

**Comment by kristenwilson** [comment]
From my perspective, the "hide deleted" option for the display screen works fine. Ian and Steve, do you still plan to pursue any additional development with this or should I close the issue?
