### ISSUE TITLE
Cannot edit Publisher Relationship Status on a TI

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#36]
e.g. from http://gokb.k-int.com/gokb/search/index?qbe=g%3Atitles&qp_name=Ambix%25&det=1

Can't edit Publisher Relationship Status

**Comment by ianibbo** [comment]
I thought we were going to do this sort of thing via workflow methods
rather than allowing users to go in and edit.. Happy to allow editing, but
not sure what the right thing to do is.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Not sure.
Workflow makes sense if adding a new publisher relationship in Web UI, but if multiple publisher relationships already added via Ingest then need someway of setting status of relationship?

Could discuss in NC?

**Comment by ianibbo** [comment]
Sure.. just sloping my shoulders really

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibo** [comment]
Done
