### ISSUE TITLE
Capture cell-level edits in Refine

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#408]
See Owen's spec: https://docs.google.com/document/d/1j8CwVxXOWAfplJnpSUrY8KZABLjuqZW4kjqc3K3OKyM/edit

**Comment by jhsolomon** [comment]
This is not working. When I add text, I do not see any edits recorded.

![image](https://cloud.githubusercontent.com/assets/13369381/10432035/ae61d47e-70d6-11e5-848a-4750a5d9d555.png)

**Comment by kristenwilson** [comment]
I can confirm that using the latest extension downloaded from http://gokb.k-int.com/gokb/api/downloadUpdate?tester=true the ability to capture cell level edits isn't showing up at all. When you edit a cell, the checkbox is gone completely.

**Comment by jhsolomon** [comment]
Retested: confirmed fix.

However, the capture edit only works if you click Apply. It does not work if you try to click "Apply to all identical cells." This could be a bit confusing for people.

**Comment by kristenwilson** [comment]
I agree this should work for both "apply" and "apply to all identical."

**Comment by sosguthorpe** [comment]
The "Apply to all identical" button is actually disabled when performing a cell level edit capture. This is because you can't apply to all identical because the edit can now take into account the data in other cells.  So there may be identical cells that aren't updated because other values in the row don't match.

Cell level edits will already actually apply everywhere the conditions are met, so may apply to more than one cell but in the same way as apply to all. I think having 2 buttons with very different functionality in normal cell edits doing the exact same thing in another scenario is bad. Hence the button being disabled and the message informing the user of the different behaviour when using the edit capture.

**Comment by kristenwilson** [comment]
Steve your logic works for me. I just didn't realize the button was disabled at first. It would be nice to have it grayed out or removed completely so it's clearer that it won't work. But in the essence of time, I think we can call this one done.
