### ISSUE TITLE
Macro will not run in Test or Live

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#486]
I am not sure why this macro will not work when I run the "apply macro" feature in Refine. It will work if I paste the code into the "Apply" field.
[Macro_Elsevier_UTF8.txt](https://github.com/k-int/gokb-phase1/files/192484/Macro_Elsevier_UTF8.txt)

Live macro: http://gokb.kuali.org/gokb/resource/show/org.gokb.cred.Macro%3A310748
Test macro: http://test-gokb.kuali.org/gokb/resource/show/org.gokb.cred.Macro%3A321319

**Comment by ianibo** [comment]
@sosguthorpe can you take a peek at this pls?

**Comment by sosguthorpe** [comment]
@jhsolomon Could you be a bit more specific, in the respect of what isn't working please? Do you receive error messages? Is it just that the macro is applied but the results aren't what you expect? I've just randomly opened 3 projects and applied this macro to each without problem.

**Comment by jhsolomon** [comment]
@sosguthorpe There is no error message, but the macro is applied and the warning and error messages are not resolved. 

Here is one example (Elsevier Freedom Collection): ScienceDirectStandard_Global_CompleteFreedomCollection_2016 03 30 txt

**Comment by sosguthorpe** [comment]
@jhsolomon  On live I applied the live macro to this project. The error count went from 4 to 2.
- One error states that the eISSN data is in the wrong format in some of the cases, which I can see after faceting that they are in deed in the wrong format (i.e. 978-0-444-51781-4)
- The second is empty package names which is also as I would have expected. Looking at the macro there is nothing in there that would resolve either of these messages and so I'm struggling to see how in what way this is misbehaving.

Can you please tell me which errors/warnings you expect to be resolved by this macro on this particular package, because as far as I can tell it looks to be working properly.

One thing I want to check with you is that you are not copying macros from live to test and vice versa. The reason is there is no guarantee that a lookup on live would yield the same component ID as a lookup on test and therefore the "same" imprint on live and test might not have the same id. This would lead to components being linked to each other incorrectly. I checked the values in the 2 imprints and they are identical, but this could be down to the fact that the live DB was copied over to test not long ago and so a lot of the components will have the same IDs on live and test. Ones created after that point though are likely to not be the same.

**Comment by sosguthorpe** [comment]
To further illustrate this. Searching for component with ID 316350:
- Live points to a TIPP: http://gokb.kuali.org/gokb/search/index?qbe=g%3Acomponents&qp_name=&qp_id=316350&qp_sid=&qp_showDeleted=on&searchAction=search&searchName=
- Test points to an ORG: http://test-gokb.kuali.org/gokb/search/index?qbe=g%3Acomponents&qp_name=&qp_id=316350&qp_sid=&qp_showDeleted=on&searchAction=search&searchName=

**Comment by jhsolomon** [comment]
Those are the same errors I saw yesterday when I pasted in the macro to the
Apply field. The only issue that I am having that is different is when I
try to run the "apply macro" and then it does not resolve any of the
errors. This macro was created for Live and I have been using it in Live. I
did try it in Test only because I was perplexed why there was such a
strange problem.

I will retest when I am able to run Refine. Thanks!

On Mar 31, 2016, at 5:07 AM, sosguthorpe notifications@github.com wrote:

@jhsolomon https://github.com/jhsolomon On live I applied the live macro
to this project. The error count went from 4 to 2.
- One error states that the eISSN data is in the wrong format in some of
  the cases, which I can see after faceting that they are in deed in the
  wrong format (i.e. 978-0-444-51781-4)
- The second is empty package names which is also as I would have
  expected. Looking at the macro there is nothing in there that would resolve
  either of these messages and so I'm struggling to see how in what way this
  is misbehaving.

Can you please tell me which errors/warnings you expect to be resolved by
this macro on this particular package, because as far as I can tell it
looks to be working properly.

One thing I want to check with you is that you are not copying macros from
live to test and vice versa. The reason is there is no guarantee that a
lookup on live would yield the same component ID as a lookup on test and
therefore the "same" imprint on live and test might not have the same id.
This would lead to components being linked to each other incorrectly. I
checked the values in the 2 imprints and they are identical, but this could
be down to the fact that the live DB was copied over to test not long ago
and so a lot of the components will have the same IDs on live and test.
Ones created after that point though are likely to not be the same.

**Comment by sosguthorpe** [comment]
@jhsolomon OK great. I was using the apply macro command when testing so this is, indeed, strange. Please do retest with the newest client and let me know how you get on.

**Comment by jhsolomon** [comment]
It works if I do not change the character encoding!!! 

Thanks for your patience on this one!
