### ISSUE TITLE
Title history line deletion deleting all lines (sometimes)

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#503]
When trying to delete and recreate a line of title history (to fix an error) I saw some strange behavior. When I deleted the title history line, it removed both lines on the title record. Normally, it should only delete the line selected. Then, when I recreated the the line I had deleted, the other line reappeared. 

You can see a screencast here: http://screencast.com/t/YnrDfotunc9

I tried the same thing on a different title, but didn't see the same problem. When I deleted a line of title history, only the appropriate line was removed.

**Comment by ianibbo** [comment]
The screencast is really great!!! very helpful, thankyou.

I think the system is doing what it thinks is right - tho that might not be
the right thing of course - This is whats happening

[Lets call this change A] "Physica B: Condensed Matter" was created when
Physcia B+C was split into "Physica B: Condensed Matter" and "Physica C:
Superconductivity" - this is one "Change" record in the title history.

We also know that

[Lets call this change B] Physica was split into "Physica A: Statisitcal
mechanicx..." and "Physica B+C"

When we view the record for "Physica B: Condensed Matter" the system tries
to construct a title history display. It does this by walking though all
the title history events, then sorting them into date order.

in this case: The first hop is easy - We're looking at "Physica B:
Condensed Matter" and we know that this title participated in change A.
From there, the system says "Did anyone involved in change A have change
records associated with them?". It turns out that Physica A+B (The title
which was split to create the record we are currently looking at) was also
involved in title change B, so that record is also listed in the title
history.

Once we delete Change A there is no path in the title history that lets us
link to Change B (Because Physica B: Condensed matter never directly
participated in Change B). So, by deleting change A, we've broken a link
that lets us trace the lineage of the title history.

Once we re-create the link, the system can re-detect the link and re-fill
in the full title history.

Sorry - not sure I'm helping :/ Think of it this way

We have a title history A -> B,C     B -> D,E    E->F    F-G

And we have a title H with no title history

When we look at record H, we see no title history. I happen to know that H
was created when title G was split into H and I, so I go and add that 1
title change.

At that point, when I go to see the title history for title H, I will
suddenly see the full history from A through to H. Similarly, and perhaps
counter intuitively, if I go to look at the record for I, I'll see the full
title history, even though I have not edited the title history there.

The reason for this is that title history events are separate to the title
records themselves. We edit them on the title screen, but they actually sit
on their own as a link between two or more titles participating in a change
record...

Does that make sense / sound right to you? How should we deal?

Cheers,
Ian.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by ianibo** [comment]
Kristen - can I close this one please? ta, e.

**Comment by kristenwilson** [comment]
Yes, I think I follow the logic. It's not that the other change was
deleted, it's just that it stopped showing on the record in question
because there was no longer a connection. It should be fine to close.

Thanks!

On Tue, May 10, 2016 at 5:17 AM, Ian Ibbotson notifications@github.com
wrote:

> Kristen - can I close this one please? ta, e.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/k-int/gokb-phase1/issues/503#issuecomment-218103204

## 

Kristen Wilson
Associate Head, Acquisitions and Discovery
North Carolina State University Libraries
919-513-3354
kristen_wilson@ncsu.edu
ORCID: http://orcid.org/0000-0002-3509-3417
