### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#555]
Should contain:
Name
RDF datatype

**Comment by ianibo** [comment]
RDF Datatype all blank on live also, save dnb which has a type of "uri". Name is present for all as per live. We only create namespaces on demand and since we only just added the code to transfer non-class-one identifers we weren't adding the others. On the next import this will be resolved, and is fixed by the "missing identifiers" commit.

**Comment by ianibo** [comment]
Reconstructed as data imported. Should all be present now. Some may have been dropped if identifiers using namespaces removed.

**Comment by jhsolomon** [comment]
Looks good!

Can you delete?:
taylor
taylor&francis
taylorandfrancis

**Comment by ianibbo** [comment]
Not sure - these are all used in real records, so removing the  might be
tricky. I'll investigate - can you close off this issue and raise a new one
for this thing specifically?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by jhsolomon** [comment]
I should clean these up so they are consistent. I'll open a new issue.
