### ISSUE TITLE
Domains

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#558]
There are more domains in Test than in Live, currently. How are these created? They seem to include all of the data elements which are:

Name
Display Name
Sort Key
Type

**Comment by ianibo** [comment]
Domains should be on test now as they were on live.

**Comment by jhsolomon** [comment]
There are 76 domains on Test and 65 on Live. 
Is that expected?

The data elements seem to match up. I'm just not sure where the extra 11 come from.

**Comment by ianibbo** [comment]
Yes, absolutely.

Domains are created dynamically and this version has new system objects
(Like Work for example).

It's important to note that because we are upgrading the system as well as
porting it things won't ever be _exactly_ as they are on live - it's more
about making sure we have not left anything behind than making sure
everything looks exactly the same..

is that OK?

Ian

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
Doodle: http://doodle.com/ianibbo

**Comment by jhsolomon** [comment]
Yes, that makes sense. I just want to make sure that not only are things not left behind that anything that is newly created was done so with a purpose :)

**Comment by jhsolomon** [comment]
Fixed
